---
- name: install packages
  become_user: aur_builder
  aur:
    name:
    - alacritty
    - bemenu
    - bemenu-wlroots
    - grim
    - grimshot
    - kde-gtk-config # Failed to load module "colorreload-gtk-module"
    - mako
    - otf-font-awesome # for waybar
    - qt5-wayland
    - slurp
    - sway
    - wallutils
    - waybar
    - wl-clipboard
    - xorg-server-xwayland

- name: install packages
  become: yes
  become_user: aur_builder
  aur:
    name: '{{ item }}'
    state: present
  with_items:
  - gtk-layer-shell-git
  # Needed for unreleased merge from back in March:
  # https://github.com/swaywm/swayidle/pull/63/files
  - swayidle-git
  - swaylock-effects
  - wev

- ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d/
    state: directory

- name: install files
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
  - {src: sway-session.target, dest: /etc/systemd/user/sway-session.target}
  - {src: sway-systemd.conf, dest: /etc/sway/config.d/90-systemd.conf}
  - {src: waybar.conf, dest: /etc/sway/config.d/10-waybar.conf}
  - {src: minimal-waybar-config, dest: /etc/xdg/waybar/config}
  - {src: swaylock.service, dest: /etc/systemd/user/swaylock.service}

- name: install swayidle.service
  ansible.builtin.template:
    src: swayidle.service
    dest: /etc/systemd/user/swayidle.service
  notify:
  - reload user service manager
  - restart swayidle.service

- name: import wob key
  become: yes
  become_user: aur_builder
  gpg_import:
    key_id: 5c6da024dde27178073ea103f4b432d5d67990e3

- name: install wob
  become: yes
  become_user: aur_builder
  aur: name=wob

- name: install ulauncher
  become: yes
  become_user: aur_builder
  aur: name=ulauncher

- name: setup ulauncher dbus activation
  ansible.builtin.copy:
    content: |
      [D-BUS Service]
      Name=net.launchpad.ulauncher
      SystemdService=ulauncher.service
      Exec=/usr/bin/ulauncher
    dest: /usr/share/dbus-1/services/net.launchpad.ulauncher.service
- name: ulauncher systemd unit
  ansible.builtin.copy:
    content: |
      [Service]
      Type=dbus
      BusName=net.launchpad.ulauncher
      ExecStart=/usr/bin/ulauncher
      ExecStartPost=busctl --user call net.launchpad.ulauncher /net/launchpad/ulauncher net.launchpad.ulauncher toggle_window
    dest: /etc/systemd/user/ulauncher.service
