version: 1

formatters:
  precise:
    format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    stream: stdout
    formatter: precise

loggers:
  synapse.storage.SQL:
    level: INFO

  twisted:
    propagate: false

root:
  level: INFO
  handlers: [console]

disable_existing_loggers: false
