version: 1

formatters:
  precise:
    format: '%(name)s:%(lineno)d - %(levelname)s - %(request)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: precise

loggers:
  synapse.storage.SQL:
    level: INFO

  twisted:
    propagate: false

root:
  level: WARN
  handlers: [console]

disable_existing_loggers: false
