---
- name: setup wired network config
  ansible.builtin.copy:
    src: 20-wired.network
    dest: /etc/systemd/network/20-wired.network
  notify: reload systemd-networkd

- name: setup chonk wireguard interface
  block:
  - ansible.builtin.template:
      src: 99-wgchonk.netdev
      dest: /etc/systemd/network/99-wgchonk.netdev
      mode: 0640
      group: systemd-network
    notify: reload systemd-networkd
  - name: setup chonk wireguard config
    ansible.builtin.copy:
      src: 99-wgchonk.network
      dest: /etc/systemd/network/99-wgchonk.network
    notify: reload systemd-networkd
  when: ansible_facts['hostname'] == 'sam-desktop'

- name: ensure systemd-networkd is running + enabled.
  ansible.builtin.systemd:
    name: systemd-networkd.service
    state: started
    enabled: yes

- name: ensure systemd-resolved is running + enabled.
  ansible.builtin.systemd:
    name: systemd-resolved.service
    state: started
    enabled: yes
