---
- name: install packages
  community.general.pacman:
    name:
    - alsa-utils
    - brightnessctl
    - gammastep
    - noto-fonts
    - noto-fonts-emoji
    - pamixer
    - playerctl
    - pulseaudio
    - pulseaudio-alsa
    - pulseaudio-zeroconf
    - pulsemixer
    - spotifyd
    - syncthing
    - ttf-jetbrains-mono
    - usbutils
    - watchman
    - xdg-utils

- name: quieten rtkit-daemon logging
  ansible.builtin.copy:
    src: quiet-rtkit-daemon-logging.conf
    dest: /etc/systemd/system/rtkit-daemon.service.d/

- name: quieten pam_unix logging
  ansible.builtin.lineinfile:
    path: /etc/pam.d/system-auth
    regexp: '^(session.*pam_unix\.so)$'
    backrefs: yes
    line: '\1 quiet'

- name: setup /var/log/sudo.log
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: 'Defaults logfile=/var/log/sudo.log'
    validate: /usr/bin/visudo -cf %s

- name: remove "good" sudo events from syslog
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: 'Defaults syslog_goodpri=none'
    validate: /usr/bin/visudo -cf %s

- name: enable+start syncthing@sam.service
  ansible.builtin.systemd:
    name: syncthing@sam.service
    enabled: yes
    state: started
