---
- hosts: localhost
  roles:
    - name: core
      tags: [core]
    - name: aur
      tags: [aur]
    - zsh
    - sublime-text
    - name: systemd-networkd
      tags: [network]
    - systemd-homed
    - i3-desktop
    - sshd
    - name: boot
      tags: [boot]
