---
- hosts: localhost
  tasks:
  - ansible.builtin.include_vars:
      file: "{{ ansible_facts['hostname'] }}.yml"
    tags: [always]

- hosts: localhost
  roles:
    - name: core
      tags: [core]
    - name: aur
      tags: [aur]
    - zsh
    - name: sublime-text
      tags: [sublime]
    - name: systemd-networkd
      tags: [network]
    - name: systemd-homed
      when: ansible_facts['hostname'] == 'sam-desktop'
    - name: sway-desktop
      tags: [desktop]
    - name: snap
      tags: [snap]
    - sshd
    - name: boot
      tags: [boot]
