---
- hosts: localhost
  roles:
    - name: core
      tags: [core]
    - zsh
    - sublime-text
    - name: systemd-networkd
      tags: [network]
    - systemd-homed
    - i3-desktop
    - sshd
    - name: dracut
      tags: [dracut]
