---
- hosts: workstations
  roles:
  - name: core
    tags: [core]
  - name: aur
    tags: [aur]
  - name: bluetooth
    tags: [bluetooth]
  - zsh
  - name: systemd-networkd
    tags: [network]
  - name: sway-desktop
    tags: [desktop]
  - name: desktop-apps
    tags: [desktop, desktop-apps]
  - name: snap
    tags: [snap]
  - sshd
  - name: boot
    tags: [boot]
  - name: 1password
    tags: [1password]
  - name: stats
    tags: [stats]

- hosts: sam-desktop
  roles:
  - name: asus-wmi-sensors
    tags: [asus]
