---
- hosts: all
  roles:
  - name: core
    tags: [core]
  - name: aur
    tags: [aur]
  - sshd
  - name: wireguard
    tags: [network, wireguard]
  - name: syncthing
    tags: [syncthing]

- hosts: workstations
  roles:
  - name: bluetooth
    tags: [bluetooth]
  - zsh
  - name: systemd-networkd
    tags: [network]
  - name: desktop-core
    tags: [desktop, desktop-core]
  - name: sway-desktop
    tags: [desktop]
  - name: desktop-apps
    tags: [desktop, desktop-apps]
  - name: snap
    tags: [snap]
  - name: boot
    tags: [boot]
  - name: stats
    tags: [stats]

- hosts: sam-desktop
  tasks:
  - name: blacklist watchdog kernel module
    ansible.builtin.copy:
      content: 'blacklist sp5100_tco'
      dest: /etc/modprobe.d/sp5100_tco.conf
  roles:
  - name: asus-wmi-sensors
    tags: [asus]

- hosts: chonk.samcday.com
  roles:
  - name: matrix-homeserver
    tags: [matrix, homeserver]
  - name: hydroxide
    tags: [hydroxide]
