---
- hosts: all
  roles:
  - {name: core,           tags: [core]}
  - {name: aur,            tags: [aur]}
  - {name: sshd,           tags: [ssh]}
  # - {name: wireguard,      tags: [network, wireguard]}
  - {name: tailscale,      tags: [network, tailscale]}
  - {name: syncthing,      tags: [syncthing]}
  - {name: restic,         tags: [restic]}
  - {name: caddy,          tags: [caddy]}
  - {name: sccache,        tags: [sccache]}

- hosts: workstations
  roles:
  - {name: bluetooth,      tags: [bluetooth]}
  - {name: zsh,            tags: [zsh]}
  - {name: networking,     tags: [network]}
  - {name: dns,            tags: [network, dns]}
  - {name: desktop-core,   tags: [desktop, desktop-core]}
  - {name: desktop-sway,   tags: [desktop, sway]}
  - {name: desktop-gnome,  tags: [desktop, gnome]}
  - {name: desktop-apps,   tags: [desktop, desktop-apps]}
  - {name: snap,           tags: [snap]}
  - {name: boot,           tags: [boot]}
  - {name: stats,          tags: [stats]}
  - {name: ecosia,         tags: [ecosia]}

- hosts: sam-desktop
  tasks:
  - name: blacklist watchdog kernel module
    ansible.builtin.copy:
      content: 'blacklist sp5100_tco'
      dest: /etc/modprobe.d/sp5100_tco.conf
  roles:
  - {name: asus-wmi-sensors,  tags: [asus]}

- hosts: chonk.samcday.com
  roles:
  - {name: matrix-homeserver, tags: [matrix, homeserver]}
  - {name: hydroxide,         tags: [hydroxide]}
