---
- hosts: localhost
  roles:
    - name: core
      tags: [core]
    - name: aur
      tags: [aur]
    - zsh
    - sublime-text
    - name: systemd-networkd
      tags: [network]
    - systemd-homed
    - name: sway-desktop
      tags: [desktop]
    - name: snap
      tags: [snap]
    - sshd
    - name: boot
      tags: [boot]
