---
- name: add sublime-text repo to pacman.conf
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [sublime-text]
      Server = https://download.sublimetext.com/arch/stable/x86_64
  notify: refresh pacman

- name: Flush handlers
  meta: flush_handlers

- name: check sublime gpg key in pacman keydb
  shell:
    cmd: pacman-key -l | grep 8A8F901A
  register: packeycheck

- name: install sublime gpg key
  shell:
    cmd: pacman-key -a && pacman-key --lsign-key 8A8F901A
    stdin: '{{ sublime_gpg_key }}'
  when: packeycheck.stdout == ''

- name: install sublime-text
  community.general.pacman:
    name: sublime-text
