---
- name: install packages
  become_user: aur_builder
  aur:
    name:
    - clevis
    - dracut
    - libpwquality
    - luksmeta
    - nmap
    - tpm2-tools

- name: configure dracut
  ansible.builtin.template:
    src: dracut.conf
    dest: /etc/dracut.conf.d/sam.conf

- name: install dracut-hook
  become: yes
  become_user: aur_builder
  aur:
    name: dracut-hook-uefi
    state: present
