---
- name: restart restic-snapshot.timer
  ansible.builtin.systemd:
    name: restic-snapshot.timer
    state: restarted
    daemon_reload: yes

- name: restart reflector
  ansible.builtin.systemd:
    name: reflector
    state: restarted
