---
- name: import Caddy signing key
  become_user: aur_builder
  become: yes
  gpg_import:
    key_id: 29D0817A67156E4F25DC24782A349DD577D586A5

- name: install Caddy
  become_user: aur_builder
  become: yes
  aur: name=caddy2

- name: Caddyfile
  ansible.builtin.copy:
    dest: /etc/caddy/Caddyfile
    content: |
      {
        email me@samcday.com
      }
      import /etc/caddy/conf.d/*.conf
  notify: reload caddy

- name: keys.d/
  ansible.builtin.file:
    path: /etc/caddy/keys.d
    state: directory
    owner: caddy
    group: root
    mode: 0700

- name: ensure Caddy is enabled
  ansible.builtin.systemd:
    name: caddy.service
    enabled: yes

- when: inventory_hostname == 'chonk.samcday.com'
  block:
  - name: chonk config.d dir
    ansible.builtin.file:
      path: /etc/caddy/conf.d/chonk.conf.d/
      state: directory

  - name: chonk Caddy config
    ansible.builtin.copy:
      dest: /etc/caddy/conf.d/chonk.conf
      content: |
        chonk.wgme {
          tls /etc/caddy/keys.d/chonk.crt /etc/caddy/keys.d/chonk.key {
            client_auth {
              trusted_ca_cert_file /etc/ca-certificates/extracted/cadir/wgme.pem
            }
          }

          @notinternal not remote_ip 192.168.250.0/24
          handle @notinternal {
            respond "Whodis?" 400 {
              close
            }
          }

          import /etc/caddy/conf.d/chonk.conf.d/*.conf
        }
    notify: reload caddy

  - name: chonk cert
    with_items: [chonk.crt, chonk.key]
    ansible.builtin.copy:
      src: '{{ item }}'
      dest: /etc/caddy/keys.d/
    notify: reload caddy
