---
- name: import Caddy signing key
  become_user: aur_builder
  become: yes
  gpg_import:
    key_id: 29D0817A67156E4F25DC24782A349DD577D586A5

- name: install Caddy
  become_user: aur_builder
  become: yes
  aur: name=caddy2

- name: Caddyfile
  ansible.builtin.copy:
    dest: /etc/caddy/Caddyfile
    content: |
      {
        email me@samcday.com
      }
      import /etc/caddy/conf.d/*
  notify: reload caddy

- name: ensure Caddy is enabled
  ansible.builtin.systemd:
    name: caddy.service
    enabled: yes
