---
- name: install packages
  become_user: aur_builder
  aur:
    name:
    - matrix-synapse
    - python-lxml
    - python-netaddr

- name: install AUR packages
  become_user: aur_builder
  become: yes
  aur: name={{ item }}
  with_items: [mautrix-signal-git]

- name: synapse log.yaml
  ansible.builtin.copy:
    src: log.yaml
    dest: /etc/synapse/log.yaml
  notify: restart synapse

- name: synapse config drop-in dir
  ansible.builtin.file:
    path: /etc/synapse/conf.d/
    state: directory

- name: synapse homeserver.yaml base
  ansible.builtin.template:
    src: homeserver.yaml
    dest: /etc/synapse/conf.d/homeserver.yaml
  notify:
  - assemble homeserver.yaml

- name: appservice dropin config
  ansible.builtin.lineinfile:
    path: /etc/synapse/conf.d/app_service_config_files.yaml
    create: yes
    line: 'app_service_config_files:'
  notify:
  - assemble homeserver.yaml

- name: start+enable synapse
  ansible.builtin.systemd:
    name: synapse
    state: started
    enabled: yes

- name: configure Caddy
  ansible.builtin.copy:
    dest: /etc/caddy/conf.d/matrix.conf
    content: |
      matrix.samcday.com:443 {
        reverse_proxy /_matrix/* http://localhost:8008
      }

      matrix.samcday.com:8448 {
        reverse_proxy http://localhost:8008
      }
  notify: reload caddy
