---
- name: install some core packages
  community.general.pacman:
    name:
    - base-devel
    - sudo
    - git
    - noto-fonts
    - firefox-developer-edition
    - pacutils

- name: wheel sudoers rule
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel ALL='
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/bin/visudo -cf %s

- name: enable en_US UTF8 locale
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: set locale.conf
  ansible.builtin.copy:
    content: 'LANG=en_US.UTF-8'
    dest: /etc/locale.conf

- name: create aur_builder user
  user:
    name: aur_builder
    group: wheel
- name: setup aur_builder sudo perms
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: install yay
  become: yes
  become_user: aur_builder
  aur:
    name: yay
    state: present
