---
- name: install some core packages
  community.general.pacman:
    name:
    - alacritty
    - base-devel
    - efibootmgr
    - element-desktop
    - firefox-developer-edition
    - git
    - jq
    - man
    - multipath-tools
    - noto-fonts
    - pacman-contrib
    - pacutils
    - ripgrep
    - strace
    - sudo
    - usbutils

- name: wheel sudoers rule
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel ALL='
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/bin/visudo -cf %s

- name: enable en_US UTF8 locale
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: set locale.conf
  ansible.builtin.copy:
    content: 'LANG=en_US.UTF-8'
    dest: /etc/locale.conf

- name: set timezone
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Europe/Berlin
    dest: /etc/localtime
    state: link

- name: blacklist watchdog kernel module
  ansible.builtin.copy:
    content: 'blacklist sp5100_tco'
    dest: /etc/modprobe.d/sp5100_tco.conf
