---
- name: import & trust sublime gpg key
  shell:
    cmd: |
      pacman-key --recv-keys 0x1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A \
      && pacman-key --lsign-key 8A8F901A

- name: add sublime-text repo to pacman.conf
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    marker: "# {mark} sublime-text"
    block: |
      [sublime-text]
      Server = https://download.sublimetext.com/arch/stable/x86_64
  notify: refresh pacman

- name: Flush handlers
  meta: flush_handlers

- name: install sublime-text
  community.general.pacman:
    name: sublime-text
