---
- name: trust totally trustworthy person on the internet # very legal, very cool
  shell:
    cmd: |
      pacman-key --recv-keys 3DEA62513C8035383A245A12E5786B42E8E5D565 \
      && pacman-key --lsign-key 3DEA62513C8035383A245A12E5786B42E8E5D565

- name: add jk-aur repo to pacman.conf
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    marker: "# {mark} jk-aur"
    block: |
      [jk-aur]
      Server = https://repo.vin.ovh/arch/$arch
  notify: refresh pacman

- name: install ungoogled-chromium
  community.general.pacman: name=ungoogled-chromium
