---
- name: reload caddy
  ansible.builtin.systemd:
    name: caddy.service
    state: reloaded

- name: reload systemd
  shell: systemctl daemon-reload

- name: restart synapse
  ansible.builtin.systemd:
    name: synapse.service
    state: restarted

- name: assemble homeserver.yaml
  ansible.builtin.assemble:
    src: /etc/synapse/conf.d
    dest: /etc/synapse/homeserver.yaml
    owner: synapse
    mode: 0400
  notify: [restart synapse]
