---
- name: install restic
  become_user: aur_builder
  aur: name=restic

- name: /etc/conf.d/restic
  ansible.builtin.copy:
    src: restic.conf.d
    dest: /etc/conf.d/restic
    mode: 0600

- name: /var/cache/restic
  ansible.builtin.file:
    path: /var/cache/restic
    state: directory
    mode: 0700

- name: restic-snapshot unit files
  with_items: [service, timer]
  ansible.builtin.copy:
    src: 'restic-snapshot.{{ item }}'
    dest: /etc/systemd/system/
  notify: restart restic-snapshot.timer

- name: disable restic-snapshot.timer
  ansible.builtin.systemd:
    name: restic-snapshot.timer
    enabled: no

- when: inventory_hostname == 'chonk.samcday.com'
  block:
  - name: restic-prune unit files
    with_items: [service, timer]
    ansible.builtin.copy:
      src: 'restic-prune.{{ item }}'
      dest: /etc/systemd/system/
    notify: restart restic-prune.timer

  - name: enable restic-prune.timer
    ansible.builtin.systemd:
      name: restic-prune.timer
      enabled: yes