---
- name: create aur_builder user
  user:
    name: aur_builder
    group: wheel

- name: setup aur_builder sudo perms
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: pretend GnuPG isn't dying a slow spasmic death
  block:
  - ansible.builtin.file:
      path: /home/aur_builder/.gnupg
      state: directory
      owner: aur_builder
  - ansible.builtin.file:
      path: /home/aur_builder/.gnupg/gpg.conf
      state: touch
      owner: aur_builder
  - ansible.builtin.lineinfile:
      path: /home/aur_builder/.gnupg/gpg.conf
      regexp: 'keyserver\s+'
      line: 'keyserver hkp://keyserver.ubuntu.com'

- name: install yay
  become: yes
  become_user: aur_builder
  aur:
    name: yay
    state: present

- name: install chezmoi
  become: yes
  become_user: aur_builder
  aur:
    name: chezmoi-git
    state: present
