---
- name: create aur_builder user
  user:
    name: aur_builder
    group: wheel

- name: don't backup aur_builder home dir
  ansible.builtin.copy:
    dest: ~aur_builder/.restic-ignore
    content: ''

- name: setup aur_builder sudo perms
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: pretend GnuPG isn't dying a slow spasmic death
  block:
  - ansible.builtin.file:
      path: /home/aur_builder/.gnupg
      state: directory
      owner: aur_builder
  - ansible.builtin.lineinfile:
      path: /home/aur_builder/.gnupg/gpg.conf
      create: yes
      regexp: 'keyserver\s+'
      line: 'keyserver hkp://keyserver.ubuntu.com'

- become: yes
  become_user: aur_builder
  block:
  - name: install stable rust compiler
    shell:
      cmd: rustup install stable
      creates: ~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
  - name: make stable rust compiler default
    ansible.builtin.lineinfile:
      path: ~/.rustup/settings.toml
      line: default_toolchain = "stable-x86_64-unknown-linux-gnu"
      regexp: default_toolchain
      insertbefore: \[overrides\]
      firstmatch: yes
  - name: install packages
    aur:
      name:
      - chezmoi
      - paru-bin
      state: present
