id: whatsapp
url: http://localhost:29318
as_token: {{ mautrix_whatsapp.as_token }}
hs_token: {{ mautrix_whatsapp.hs_token }}
sender_localpart: {{ mautrix_whatsapp.sender_localpart }}
rate_limited: false
namespaces:
  users:
  - regex: ^@whatsapp_[0-9]+:samcday.com$
    exclusive: true
  - regex: ^@whatsappbot:samcday.com$
    exclusive: true
