---
- name: restart sccache-server.service
  ansible.builtin.systemd:
    name: sccache-server.service
    daemon_reload: yes
    state: restarted
  ignore_errors: yes

- name: restart sccache-scheduler.service
  ansible.builtin.systemd:
    name: sccache-scheduler.service
    daemon_reload: yes
    state: restarted
  ignore_errors: yes
