---
- name: install gtk-layer-shell-git
  become: yes
  become_user: aur_builder
  aur:
    name: gtk-layer-shell-git
    state: present

# Needed for unreleased merge from back in March:
# https://github.com/swaywm/swayidle/pull/63/files
- name: install swayidle-git
  become: yes
  become_user: aur_builder
  aur:
    name: swayidle-git
    state: present

- name: install packages
  community.general.pacman:
    name:
    - alacritty
    - bemenu
    - bemenu-wlroots
    - kde-gtk-config # Failed to load module "colorreload-gtk-module"
    - mako
    - otf-font-awesome # for waybar
    - qt5-wayland
    - sway
    - wallutils
    - waybar

- name: install swaylock-effects
  become: yes
  become_user: aur_builder
  aur:
    name: swaylock-effects
    state: present

- name: install jetbrains-toolbox
  become: yes
  become_user: aur_builder
  aur:
    name: jetbrains-toolbox
    state: present

- ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d/
    state: directory

- name: install files
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
  - {src: sway-session.target, dest: /etc/systemd/user/sway-session.target}
  - {src: sway-systemd.conf, dest: /etc/sway/config.d/90-systemd.conf}
  - {src: waybar.conf, dest: /etc/sway/config.d/10-waybar.conf}
  - {src: autologin.conf, dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf}
  - {src: minimal-waybar-config, dest: /etc/xdg/waybar/config}
  - {src: swaylock.service, dest: /etc/systemd/user/swaylock.service}

- name: install swayidle.service
  ansible.builtin.template:
    src: swayidle.service
    dest: /etc/systemd/user/swayidle.service
  notify:
  - reload user service manager
  - restart swayidle.service

- ansible.builtin.file:
    path: /usr/share/backgrounds/macOS
    state: directory

- name: install mojave dynamic wallpaper
  ansible.builtin.unarchive:
    remote_src: yes
    src: https://github.com/japamax/gnome-kde-dynamic-wallpaper-mojave/tarball/master
    dest: /usr/share/backgrounds/macOS
    extra_opts: [--strip-components=1]
    creates: /usr/share/backgrounds/macOS/mojave-timed.xml

- name:
  ansible.builtin.file:
    path: /usr/share/backgrounds/macOS/mojave.xml
    state: absent

- name: import wob key
  become: yes
  become_user: aur_builder
  shell:
    cmd: curl 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x5c6da024dde27178073ea103f4b432d5d67990e3' | gpg --import
    warn: false

- name: install wob
  become: yes
  become_user: aur_builder
  aur: name=wob

- name: install ulauncher
  become: yes
  become_user: aur_builder
  aur: name=ulauncher

- name: setup ulauncher dbus activation
  ansible.builtin.copy:
    content: |
      [D-BUS Service]
      Name=net.launchpad.ulauncher
      SystemdService=ulauncher.service
      Exec=/usr/bin/ulauncher
    dest: /usr/share/dbus-1/services/net.launchpad.ulauncher.service
- name: ulauncher systemd unit
  ansible.builtin.copy:
    content: |
      [Service]
      Type=dbus
      BusName=net.launchpad.ulauncher
      ExecStart=/usr/bin/ulauncher
      ExecStartPost=busctl --user call net.launchpad.ulauncher /net/launchpad/ulauncher net.launchpad.ulauncher toggle_window
    dest: /etc/systemd/user/ulauncher.service

- name: trust totally trustworthy person on the internet # very legal, very cool
  shell:
    cmd: |
      pacman-key --recv-keys 3DEA62513C8035383A245A12E5786B42E8E5D565 \
      && pacman-key --lsign-key 3DEA62513C8035383A245A12E5786B42E8E5D565

- name: add jk-aur repo to pacman.conf
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [jk-aur]
      Server = https://repo.vin.ovh/arch/$arch
  notify: refresh pacman

- name: install ungoogled-chromium
  community.general.pacman: name=ungoogled-chromium
