---
- name: install packages
  community.general.pacman:
    name:
    - gdm
    - sway
    - swayidle
    - swaylock
    - xorg-server-xwayland

- name: enable gdm
  ansible.builtin.systemd:
    name: gdm.service
    enabled: yes
