---
- name: install gtk-layer-shell-git
  become: yes
  become_user: aur_builder
  aur:
    name: gtk-layer-shell-git
    state: present

- name: install packages
  community.general.pacman:
    name:
    - alacritty
    - bemenu
    - bemenu-wlroots
    - firefox-developer-edition
    - kde-gtk-config # Failed to load module "colorreload-gtk-module"
    - otf-font-awesome # for waybar
    - sway
    - swayidle
    - waybar

- name: install swaylock-effects
  become: yes
  become_user: aur_builder
  aur:
    name: swaylock-effects
    state: present

- ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d/
    state: directory

- name: install files
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
  - {src: sway-session.target, dest: /etc/systemd/user/sway-session.target}
  - {src: swayidle.service, dest: /etc/systemd/user/swayidle.service}
  - {src: sway-systemd.conf, dest: /etc/sway/config.d/90-systemd.conf}
  - {src: waybar.conf, dest: /etc/sway/config.d/10-waybar.conf}
  - {src: autologin.conf, dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf}
  - {src: minimal-waybar-config, dest: /etc/xdg/waybar/config}
