---
- name: /etc/sccache-scheduler.conf
  ansible.builtin.template:
    src: scheduler.conf
    dest: /etc/sccache-scheduler.conf
    mode: 0600
  notify: restart sccache-scheduler.service

- name: sccache-scheduler.service
  ansible.builtin.copy:
    dest: /etc/systemd/system/sccache-scheduler.service
    content: |
      [Service]
      Environment=SCCACHE_NO_DAEMON=1
      Environment=RUST_LOG=info
      ExecStart=/usr/bin/sccache-dist scheduler --config /etc/sccache-scheduler.conf
  notify: restart sccache-scheduler.service

- name: enable sccache-scheduler.service
  ansible.builtin.systemd:
    name: sccache-scheduler.service
    enabled: yes
