---
- name: setup wgme
  block:
  - ansible.builtin.template:
      src: 99-wgme.netdev
      dest: /etc/systemd/network/99-wgme.netdev
      mode: 0640
      group: systemd-network
    notify:
    - reload systemd-networkd
  - ansible.builtin.template:
      src: 99-wgme.network
      dest: /etc/systemd/network/99-wgme.network
    notify:
    - reload systemd-networkd

- name: generate .wgme host entries
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].wgme.ip }} {{ item }}.wgme"
  loop: "{{ groups['all'] }}"
