---
- name: install openssh
  become_user: aur_builder
  aur: name=openssh

- name: enable+start sshd
  ansible.builtin.systemd:
    name: sshd
    enabled: yes
    state: started

- name: StreamLocalBindUnlink yes
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: StreamLocalBindUnlink yes
    regexp: StreamLocalBindUnlink
    validate: sshd -tf %s
